# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Newsroom"
  weight = 1

[[main]]
  name = "News"
  url = "http://dev.kompetenzwasser.de/en/newsroom/news"
  weight = 2

[[main]]
  name = "Events"
  url = "http://dev.kompetenzwasser.de/en/newsroom/veranstaltungen"
  weight = 3

[[main]]
  name = "Annual Reports"
  url = "http://dev.kompetenzwasser.de/en/newsroom/jahresberichte"
  weight = 4

[[main]]
  name = "Media"
  url = "http://dev.kompetenzwasser.de/en/newsroom/presse"
  weight = 5


[[main]]
  name = "Research"
  weight = 6

[[main]]
  name = "Projects"
  url = "http://dev.kompetenzwasser.de/en/forschung/projekte"
  weight = 7

[[main]]
  name = "Products"
  url = "http://dev.kompetenzwasser.de/en/forschung/produkte"
  weight = 8
  
[[main]]
  name = "Publications"
  url = "/publication"
  weight = 9

[[main]]
  name = "About"
  weight = 10

[[main]]
  name = "Organization"
  url = "http://dev.kompetenzwasser.de/en/ueber-uns/unternehmen"
  weight = 11

[[main]]
  name = "Team"
  url = "http://dev.kompetenzwasser.de/en/ueber-uns/team"
  weight = 12

[[main]]
  name = "Network"
  url = "http://dev.kompetenzwasser.de/en/ueber-uns/netzwerk"
  weight = 13

#[[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 5

#[[main]]
#  name = "Tags"
#  url = "#tags"
#  weight = 6

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
