# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Newsroom"
  weight = 1

[[main]]
  name = "News"
  url = "https://dev.kompetenzwasser.de/de/newsroom/news"
  weight = 2

[[main]]
  name = "Veranstaltungen"
  url = "https://dev.kompetenzwasser.de/de/newsroom/veranstaltungen"
  weight = 3

[[main]]
  name = "Jahresberichte"
  url = "https://dev.kompetenzwasser.de/de/newsroom/jahresberichte"
  weight = 4

[[main]]
  name = "Presse"
  url = "https://dev.kompetenzwasser.de/de/newsroom/presse"
  weight = 5


[[main]]
  name = "Forschung"
  weight = 6

[[main]]
  name = "Projekte"
  url = "https://dev.kompetenzwasser.de/de/forschung/projekte"
  weight = 7

[[main]]
  name = "Dienstleistungen"
  url = "https://dev.kompetenzwasser.de/de/forschung/dienstleistungen"
  weight = 8
  
[[main]]
  name = "Publikationen"
  url = "/publication"
  weight = 9

[[main]]
  name = "Über uns"
  weight = 10

[[main]]
  name = "Unternehmen"
  url = "https://dev.kompetenzwasser.de/de/ueber-uns/unternehmen"
  weight = 11

[[main]]
  name = "Team"
  url = "https://dev.kompetenzwasser.de/de/ueber-uns/team"
  weight = 12

[[main]]
  name = "Netzwerk"
  url = "https://dev.kompetenzwasser.de/de/ueber-uns/netzwerk"
  weight = 13

#[[main]]
#  name = "Tutorials"
#  url = "/tutorial/"
#  weight = 5

#[[main]]
#  name = "Tags"
#  url = "#tags"
#  weight = 6

#[[main]]
#  name = "Contact"
#  url = "#contact"
#  weight = 7

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 7
