[build]
  publish = "public"
  command = "hugo --gc --minify"

# URL: https://publications.kompetenz-wasser.de/ 
[context.production.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_ENV = "production"
  HUGO_BASEURL = "https://publications.kompetenz-wasser.de/"
  HUGO_ENABLEGITINFO = "false"
  ALGOLIA_INDEX_NAME = "prod_kwb_pubs_de"
  
[context.production]
  command = "hugo --gc --minify && algolia/run-index-upload.sh -p"

# URL: https://dev--kwb.netlify.app/  
[context.dev.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_ENV = "dev"
  HUGO_ENABLEGITINFO = "false"
  # Algolia index name needed to run algolia/run-index-upload.sh
  ALGOLIA_INDEX_NAME = "dev_kwb_pubs_de"

[context.dev]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && algolia/run-index-upload.sh -p -u $DEPLOY_PRIME_URL"

[context.deploy-preview]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_ENV = "dev"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.70.0"
  HUGO_ENV = "dev"

[[headers]]
  for = "*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
  for = "index.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

